### PR TITLE
Adding a Breakfast Recipe

### PR DESCRIPTION
**Pull request by jravellana**
🎯 Objective

Submitting a recipe for a breakfast item

🛠️ Changes made

Updated entry to include a recipe for breakfast tacos featuring serving size, time to prepare, ingredients, steps, notes and more! 

👥 Who needs to review this Pull Request?

@cake0521  @anjuved can you all review and approve if it looks good?

### CODE REVIEW

**Comment by anjuved** [comment]
thanks @jravellana - I added some edits in a commit but now I think it is good to go once @cake0521 takes a look!

**Review by cake0521 — APPROVED** [review]
This looks good!

**Review by jravellana — COMMENTED** [review]
Lol okay fair

**Comment by jravellana** [comment]
Awesome, @anjuved can you add a 2nd approval so we can then merge?

**Comment by anjuved** [comment]
@jravellana - already did above, and also added my changes in a commit. Let's give @luke-hedlund and @maryyyao a chance to commit to the pull request before we merge?

**Pull request merged**
