### PR TITLE
updated lunch

### PR DESCRIPTION
**Pull request by anjuved**
Changed to white bread instead of wheat bread since I like white bread.

## 🎯 Objective

Changed to white bread instead of wheat bread since I like white bread.

## 🛠️ Changes made

Changed to white bread instead of wheat bread since I like white bread.

## 👥 Who needs to review this Pull Request? 
@maryyyao @luke-hedlund 
_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by jravellana — APPROVED** [review]
White bread is definitely cheaper too!

**Comment by jravellana** [comment]
@maryyyao Can you approve and merge this pull request? I think that will actually bring us to a close on this assignment!

**Comment by maryyyao** [comment]
Merged! Woooo

**Comment by maryyyao** [comment]
@jravellana see above! (#merged)

**Pull request merged**
